# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = ""
application_url = "https://random.trycloudflare.com"
embedded = true
name = "test_app_survey_template"
handle = "test_app_survey_template"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_draft_orders,write_draft_orders,read_orders,write_orders,customer_read_orders,customer_write_orders,customer_read_draft_orders,customer_read_customers,customer_write_customers,write_customers"

[auth]
redirect_urls = [
  "https://random.trycloudflare.com/auth/callback",
  "https://random.trycloudflare.com/auth/shopify/callback",
  "https://random.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://random.trycloudflare.com/api/proxy"
subpath = "api"
prefix = "apps"

[pos]
embedded = false
